import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    flex: 1,
    width: "100%",
    height: "100%",
  },
  headerSubText: {
    fontSize: 15,
    textAlign: "center",
    alignContent: "center",
    justifyContent: "center",
    marginTop: 5,
    color: "#fff",
  },
  headerText: {
    color: "#fff",
    fontWeight: "700",
    textAlign: "center",
    alignContent: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 5,
    fontSize: 30,
    textShadowColor: "blue",
  },
  textSpace: {
    marginTop: 240,
  },
  input: {
    width: 300,
    marginBottom: 20,
    height: 50,
    borderColor: "black",
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    backgroundColor:"white",
  },
  icon: {
    marginHorizontal: 190,
    marginVertical: 30,
  },
  image: {
    position:"absolute",
    top:105,
    right:-120,
    height: 200,
    width: 320,
    marginHorizontal: 110,
  },
  button: {
    position: "absolute",
    bottom: -90,
    left: 100,
    marginTop: 20,
    width: "50%",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 10,
    elevation: 3,
    backgroundColor: "#000",
  },
  text: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: "bold",
    letterSpacing: 0.25,
    color: "white",
  },
});
